namespace Ocdi.Alphaess.Models;


public class CustomSetting
{
    public string sys_sn { get; set; }
    public string ems_version { get; set; }
    public string charge_workdays { get; set; }
    public int grid_charge { get; set; }
    public string time_chaf1a { get; set; }
    public string time_chae1a { get; set; }
    public string time_chaf2a { get; set; }
    public string time_chae2a { get; set; }
    public string bakbox_ver { get; set; }
    public int ctr_dis { get; set; }
    public string time_disf1a { get; set; }
    public string time_dise1a { get; set; }
    public string time_disf2a { get; set; }
    public string time_dise2a { get; set; }
    public float bat_high_cap { get; set; }
    public float bat_use_cap { get; set; }
    public string charge_weekend { get; set; }
    public int grid_Charge_we { get; set; }
    public string time_cha_fwe1a { get; set; }
    public string time_cha_ewe1a { get; set; }
    public string time_cha_fwe2a { get; set; }
    public string time_cha_ewe2a { get; set; }
    public float bat_highcap_we { get; set; }
    public int ctr_dis_we { get; set; }
    public string time_dis_fwe1a { get; set; }
    public string time_dis_ewe1a { get; set; }
    public string time_dis_fwe2a { get; set; }
    public string time_dis_ewe2a { get; set; }
    public float bat_usecap_we { get; set; }
    public object basic_mode_jp { get; set; }
    public object peace_mode_jp { get; set; }
    public object vpp_mode_jp { get; set; }
    public string channel1 { get; set; }
    public string control_mode1 { get; set; }
    public string start_time1a { get; set; }
    public string end_time1a { get; set; }
    public string start_time1b { get; set; }
    public string end_time1b { get; set; }
    public string date1 { get; set; }
    public string charge_soc1 { get; set; }
    public string ups1 { get; set; }
    public int switch_on1 { get; set; }
    public int switch_off1 { get; set; }
    public string delay1 { get; set; }
    public string duration1 { get; set; }
    public string pause1 { get; set; }
    public string channel2 { get; set; }
    public string control_mode2 { get; set; }
    public string start_time2a { get; set; }
    public string end_time2a { get; set; }
    public string start_time2b { get; set; }
    public string end_time2b { get; set; }
    public string date2 { get; set; }
    public string charge_soc2 { get; set; }
    public string ups2 { get; set; }
    public int switch_on2 { get; set; }
    public int switch_off2 { get; set; }
    public string delay2 { get; set; }
    public string duration2 { get; set; }
    public string pause2 { get; set; }
    public int l1_priority { get; set; }
    public int l2_priority { get; set; }
    public int l3_priority { get; set; }
    public float l1_soc_limit { get; set; }
    public float l2_soc_limit { get; set; }
    public float l3_soc_limit { get; set; }
    public int charge_mode2 { get; set; }
    public int charge_mode1 { get; set; }
    public int backupbox { get; set; }
    public string minv { get; set; }
    public string mbat { get; set; }
    public int generator { get; set; }
    public int gc_output_mode { get; set; }
    public int generator_mode { get; set; }
    public int gc_soc_start { get; set; }
    public int gc_soc_end { get; set; }
    public int gc_time_start { get; set; }
    public int gc_time_end { get; set; }
    public int gc_charge_power { get; set; }
    public int gc_rated_power { get; set; }
    public int dg_cap { get; set; }
    public int dg_frequency { get; set; }
    public int gc_rate_percent { get; set; }
    public object chargingpile { get; set; }
    public float currentsetting { get; set; }
    public int chargingmode { get; set; }
    public object charging_pile_list { get; set; }
    public int peak_fill_en { get; set; }
    public float peakvalue { get; set; }
    public float fillvalue { get; set; }
    public float delta { get; set; }
    public string peak_s1a { get; set; }
    public string peak_e1a { get; set; }
    public string peak_s2a { get; set; }
    public string peak_e2a { get; set; }
    public string fill_s1a { get; set; }
    public string fill_e1a { get; set; }
    public string fill_s2a { get; set; }
    public string fill_e2a { get; set; }
    public float pm_offset { get; set; }
    public float pm_max { get; set; }
    public float pm_offset_en { get; set; }
    public string pm_offset_s1a { get; set; }
    public string pm_offset_e1a { get; set; }
    public string pm_offset_s2a { get; set; }
    public string pm_offset_e2a { get; set; }
    public int stoinv_type { get; set; }
    public int loadcut_soc { get; set; }
    public int loadtied_soc { get; set; }
    public int ac_tied { get; set; }
    public int soc_50_flag { get; set; }
    public int auto_soccalib_en { get; set; }
}
